[package]
name = "phys engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.17.3"

[profile.release]
opt-level = "z"     # Optimize for size
lto = true          # Link-time optimization
codegen-units = 1   # Better optimization
strip = true        # Remove debug symbols



